In [2]:
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn.datasets import fetch_openml

The MNIST dataset is a well-known benchmark dataset in the field of machine learning and consists of 70,000 grayscale images of handwritten digits (0-9), each represented as a 28x28 pixel matrix (784 total features per image).

In [10]:
mnist, labels = fetch_openml("mnist_784", version=1, return_X_y=True, as_frame=False)


In [15]:
print(mnist.shape)
print(mnist)

(70000, 784)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [16]:
mnist   = mnist.astype("float32") / 255.0
labels  = labels.astype(int)
num_pcs = 30


In [17]:
print(mnist)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
def pca(X, num_components):
    X_meand = 